README.md
beeline/__init__.py
beeline/test_beeline.py
beeline/trace.py

Goals
* give beeline users the flexibility to control what data actually gets sent to Honeycomb
* add metadata to all or some events, no matter how they were generated
* remove fields they don't want in their dataset
* scrub or mask sensitive data before it gets sent
* allow beeline users to apply additional sampling above what the beeline is doing
* or tell the beeline not to sample and use their own sampling algorithm
Event modification and sampling are sufficiently different that we will separate them into two hooks.

Add sampler and presend hooks

---

beeline/middleware/flask/__init__.py
beeline/version.py
setup.py

Still need to understand why the value wasn't present as expected and how to work around that, but this will at least give empty strings instead of rendering the Beeline unusable.

Use dict get instead of direct dict access in Flask init

---

beeline/__init__.py
beeline/internal.py
beeline/middleware/awslambda/__init__.py
beeline/middleware/awslambda/test_awslambda.py
beeline/middleware/bottle/__init__.py
beeline/middleware/django/__init__.py
beeline/middleware/flask/__init__.py
beeline/test_beeline.py

We currently use a number of scattered global variables to implement the beeline. Adding new things is awkward because you have to reach into the beeline module's global state from other modules, and you can't always trust that things are initialized correctly. So to make this easier to maintain going forward I am wrapping up global state into a single object. Other modules can use the public method `get_beeline` to get the global beeline, or create an object of their own if necessary.
Also moved some internal methods to a new `internal` module to discourage users from using them (had seen this before with `_new_event` and `_send_event`)

Refactor fragmented global state into Beeline object

---

beeline/__init__.py
beeline/test_beeline.py
beeline/test_trace.py
beeline/trace.py

Below paves the way for easier implementation of inter-service tracing and auto-instrumentation. I will follow up with another diff based on this to add the required plumbing for our middleware, and also add instrumentation for the `requests` lib as a starter for automagic propagation.
Based heavily off of https://github.com/honeycombio/beeline-nodejs/blob/master/docs/API.md - provide a public API for traces including:
starting/finishing spans
starting/finishing traces
marshaling/unmarshaling trace context
adding custom context
Does away with the dual event and trace stacks - everything is a span now, so there's one stack of spans to keep track of. There are some deprecated functions kept around that are based on the old state model, because it's possible someone out there is using them, …

[tracing] Add public trace API

---

beeline/__init__.py
beeline/patch/requests.py
beeline/trace.py

Depends on https://github.com/honeycombio/beeline-python/pull/27
Adds a simple wrapper around `requests.sessions.Session.request` - will fetch the current thread's trace context - if it exists - marshaling it into a header called `X-Honeycomb-Trace`.
To use:
```
import beeline
from beeline.patch import requests
import requests
beeline.init(...)
requests.get()
requests.post()
```

[patch] add requests instrumentation

---

beeline/__init__.py
beeline/middleware/awslambda/test_awslambda.py
beeline/test_beeline.py
beeline/version.py
setup.py

Accidentally left this out in 2.0.

[api] add marshal_trace_context to top-level API

---

beeline/test_trace.py
beeline/trace.py
beeline/version.py
setup.py

It's possible for the context manager to be interrupted before `span` is set (i.e. through an exception). Put defenses in to prevent span attributes from being accessed if span is never set.

Fix crash in contextmanager if span is None

---

.travis.yml
beeline/middleware/django/__init__.py
beeline/test_trace.py
pylint.rc

There are some very simple things that we can catch with pylint, so let's make it a part of our CI testing. I generated this config to only look at pylint errors. Over time we might want to up our pylint sensitivity, but that'll take more than an hour so I'm punting it for today.
This will initially fail. Will rebase after https://github.com/honeycombio/beeline-python/pull/47 lands and fix remaining errors.

[setuptools] enforce lint errors in CI checks

---

beeline/test_trace.py
beeline/trace.py
beeline/version.py
setup.py

Fixes https://github.com/honeycombio/beeline-python/issues/50
This was an oversight and I'm considering it a bugfix, hence the patch version change

[trace] tracer context manager should yield the span object

---

beeline/__init__.py

While working on https://github.com/honeycombio/beeline-python/issues/51, I've figured
that the current tracer does not really works with already decorated functions.
(The decorator I had changed the function in specific way, allowing fn.clear_cache being called.
This beeline.traced erased these changes).
I don't think there is anything contentious here since it's a good practice to wrap
decorators with this anyway.

Fix tracing already decorated functions with beeline.traced

---

beeline/internal.py
beeline/middleware/awslambda/__init__.py
beeline/middleware/django/__init__.py
beeline/middleware/flask/__init__.py
beeline/patch/requests.py
beeline/patch/tornado.py
beeline/test_internal.py
beeline/trace.py
beeline/version.py
setup.py

We try to stringify exceptions that occur in a span, but we can't control the contents of the exceptions. In python2.7, an exception with a utf-8 string can break when we try to call str() on it. Adds a wrapper to make this safer.

[bugfix] safer handling of utf-8 encoded exceptions

---

beeline/version.py
setup.py

Fixes https://github.com/honeycombio/beeline-python/issues/58
The newer libhoney has a fallback handler for types that the builtin json encoder doesn't understand. This should fix serialization of things like datetime objects.

Bump dependency on libhoney to 1.7.0

---

beeline/middleware/django/__init__.py
beeline/version.py
setup.py

Django middleware provides an optional `process_view` hook (see here: https://docs.djangoproject.com/en/2.1/topics/http/middleware/#process-view) - we can use this to extract the view name that is being called and add it as another field to the event that represents the request. It also provides `view_args` and `view_kwargs` but I'd rather not log these by default as they may contain sensitive data.

[django] include view name in built-in django instrumentation

---

CHANGELOG.md
beeline/middleware/flask/__init__.py
beeline/version.py
setup.py

Fixes https://github.com/honeycombio/beeline-python/issues/62.
Bumps version to 2.5.1

[middleware] support dict parameters type in flask middleware

---

beeline/middleware/werkzeug/__init__.py

This is basically a copy of the bottle middleware. It implements the general WSGI middleware interface. Rather than point Werkzeug users to the bottle middleware, we should just have a Werkzeug middleware. I'd like to build on this in the future (adding db instrumentation, etc) but this is a starting point.

[middleware] add initial Werkzeug support

---

CHANGELOG.md
beeline/test_trace.py
beeline/trace.py
beeline/version.py
setup.py

A couple of differences in the deterministic sampler implementation meant that the python beeline would produce different sampling decisions than the go, node, ruby, etc beelines. After adding a test in https://github.com/honeycombio/beeline-go/pull/68, also implemented the same test here and fixed the issues that it detected.

[tracing] add interop test, fix deterministic sampler

---

beeline/__init__.py
beeline/test_trace.py
beeline/trace.py

Based off of `AddRollupField` in the go beeline (https://github.com/honeycombio/beeline-go/blob/master/trace/trace.go). Docs inline.
I intentionally made `add_rollup_field` a method only on tracer (and beeline), not each span, since it needs the full trace context. Same as `add_trace_field`.
Test Plan: Didn't test it in real life. Did write a unit test.

Add `add_rollup_field` API

---

beeline/middleware/django/__init__.py

By subclassing `django.HoneyMiddlewareBase`, it is now possible to
change the context that gets sent to Honeycomb.
See #72.

Allow overriding context for Django Middleware.

---

beeline/middleware/awslambda/__init__.py

Hi,
When doing unit tests on Honeycomb-instrumented Lambdas, the tests would fail to run due to the `context` object not being populated.
This PR adds a blank default in case the attributes cannot be used.

Lambda instrumentation graceful fail

---

CHANGELOG.md
beeline/middleware/bottle/__init__.py
beeline/middleware/bottle/test_bottle.py
beeline/middleware/django/__init__.py
beeline/middleware/django/test_django.py
beeline/middleware/flask/__init__.py
beeline/middleware/flask/test_flask.py
beeline/middleware/werkzeug/__init__.py
beeline/middleware/werkzeug/test_werkzeug.py
beeline/version.py
setup.py

A mixed bag here:
- extend the capability of new `get_context_*` functions in Flask, Bottle, and Werkzeug middlewares
- Drop `request.POST.dict()` from default instrumentation in django by default
- Adds initial test structure for middleware. At best, this tests that the middleware code executes and doesn't crash due to trivial runtime errors, but there's a long way to go here.

[middleware] enable subclassing of other middleware implementations, remove POST in django

---

beeline/middleware/django/__init__.py

Modify Django middleware to support multiple databases.
Uses `contextlib.ExitStack` which is only available from Python 3.3+ but since this portion of code relies on Django 2.0 which only supports Python 3.4+, the exception catcher can be reused.

Modify Django middleware to support multiple databases

---

beeline/middleware/flask/__init__.py

Both `before_cursor_execute` and `after_cursor_execute` exit early 
if there is no `current_app`, but `handle_error` tries to finish
the span even if there is no `current_app`. This caused an
`AttributeError` when I was using beeline-python in the context of a
multi-threaded application, since when we used `HoneyDBMiddleware` off
of the thread it had been initialized on, `self.state.span` was never
set. We could probably also fix this by using `getattr` on `self.state`
before accessing `span`, but this seems more consistent with how the
other methods operate.

[middleware] Don't try to access self.state.span in handle_error of Flask DB middleware if there is no current_app

---

.circleci/config.yml
beeline/__init__.py
beeline/aiotrace.py
beeline/test_async.py
beeline/test_beeline.py
beeline/test_suite.py
beeline/test_trace.py
beeline/trace.py
setup.py

This change adds `AsyncioTracer`, which is chosen instead of
`SynchronousTracer` as the tracer implementation if beeline is
initialized from within an `asyncio` event loop.
`AsyncioTracer` stores its trace state in a context variable instead
of in thread local storage. This requires the `contextvars` module,
which was added in Python 3.7. Otherwise the implementation is shared
with `SynchronousTracer`. The trace state implementation is moved into
the `Trace` class to support both implementations.
Context variable assignments are unique per `asyncio` task, allowing
separate trace state per task. New tasks automatically receive the
same context variable bindings when they are created, which is not
what you want for the trace state, since they need to be able to
diverge between tasks. To fix …

Add support for tracing asynchronous code

---

beeline/middleware/flask/__init__.py

This is the case when using PyODBC and maybe others
Fixes #90

Fixes AttributeError when cursor.lastrowid doesn't exist

---

beeline/trace.py

It looks like the behavior of _should_sample [was fixed a while back](https://github.com/honeycombio/beeline-python/commit/908942fb838867b2ab9b40c090f0374091c5b410) but the comment wasn't updated to reflect that. 
Signed-off-by: Irving Popovetsky <irving@honeycomb.io>

Fix a comment in the _should_sample function: the first 4 bytes are taken not the last 4

---

beeline/trace.py

When reserving a trace_field from CTX the names all ready start with the prefix app. so we receive duplicate prefix **app.app.**
example:
AWS lambda x is using **add_trace_field("id", "i-1")**  (in honeycomb we will see it as **app.id** as expected).
lambda x sending its CTX to lambda y, in honeycomb we will see **app.app.id** and not **app.id** as expected

add check if the app prefix exists

---

beeline/patch/urllib.py

This adds a Beeline patch for `urllib` (based on the `requests` patch).  This enables hotpatching of, for instance, `oauthlib`.
Note that this only works on Python3, which calls it, in fact, `urllib`, not `urllib2`.

patch: add urllib patch

---

beeline/middleware/flask/__init__.py

Fixes #101.
Note that I've tested this approach in my code (e.g. https://github.com/pebble-dev/rebble-appstore-api/blob/master/appstore/__init__.py#L40 ), but I confess that I have not tested precisely this diff (my staging environment is not quite set up right to take a different source of beeline).  But I'm pretty sure it ought to work.

flask: capture route

---

beeline/aiotrace.py
beeline/test_beeline.py
beeline/trace.py

At present, instrumenting a generator function with `@beeline.traced` which calls other generator functions results in the following odd behaviour:
* The generator function's timing is the time taken to return the generator, not the time the generator takes
* The generator’s span is not the parent of any child spans

add instrumentation to generator functions

---

beeline/__init__.py

Some people have contextvars backported, so it's no longer a useful 3.7 canary; instead just probe directly for the method we use.

If <3.7 and no get_running_loop, return false.

---

.bumpversion.cfg
README.md
beeline/version.py
poetry.lock
pyproject.toml

Use `bump2version` to manage version numbers, to avoid skew between `pyproject.toml` and `version.py`.

Use bump2version to manage versions

---

.bumpversion.cfg
CHANGELOG.md
beeline/__init__.py
beeline/middleware/awslambda/__init__.py
beeline/middleware/awslambda/test_awslambda.py
beeline/middleware/bottle/__init__.py
beeline/middleware/bottle/test_bottle.py
beeline/middleware/django/__init__.py
beeline/middleware/django/test_django.py
beeline/middleware/flask/__init__.py
beeline/middleware/flask/test_flask.py
beeline/middleware/werkzeug/__init__.py
beeline/middleware/werkzeug/test_werkzeug.py
beeline/middleware/wsgi.py
beeline/patch/requests.py
beeline/patch/test_requests.py
beeline/patch/test_urllib.py
beeline/patch/urllib.py
beeline/propagation/__init__.py
beeline/propagation/honeycomb.py
beeline/propagation/test_honeycomb.py
beeline/propagation/test_propagation.py
beeline/test_beeline.py
beeline/test_trace.py
beeline/trace.py
beeline/version.py
poetry.lock
pyproject.toml

PR for implementing user-customizable hooks for HTTP header parsing and propagation.
Per discussion with @paulosman, the goal here is to get the code change in. We know that we will want to improve the tests and the documentation, but since the overall test quality/documentation here is poor we don't want to make this PR bigger with testing.
I have done manual testing by implementing python services in https://github.com/honeycombio/example-greeting-service/pull/1 - these will hopefully become the foundation of integration tests that will make our automated testing situation more robust in the future.
* New `beeline` configuration parameters for `http_trace_parse_hook` and `http_trace_propagation_hook`
* New `propagate_and_start_trace` function for use by middleware to invoke the …

http header hooks

---

CHANGELOG.md
beeline/__init__.py
beeline/propagation/test_w3c.py
beeline/propagation/w3c.py

This implements w3c-compatible trace header hooks on top of the new `http_trace_parser_hook` and `http_trace_propagation_hook`.
Note that this is the minimal implementation for interoperability - it only propagates traceflags and tracestate, not making any attempt to parse them or add to them.
I have implemented basic tests, and verified by running them the example-greeting-service and verifying that it works to create a valid trace when inserted between otel go services.

w3c hooks and basic tests

---

beeline/middleware/awslambda/__init__.py
beeline/middleware/awslambda/test_awslambda.py

Currently the Lambda wrapper always records the incoming event and the lambda response (if present).
That behavior may be undesirable if the input/output is very large.
This PR updates the Lambda wrapper to include two parameters (`record_input` and `record_output`) which allow the customization of that behavior.  These parameters default to `True`, leaving the default behavior unchanged.

Update Lambda wrapper to allow omission of input/output fields

---

beeline/trace.py

**What**
Add app.exception_traceback to context when an exception is thrown 
**Why?**
`app.exception_type` and `app.exception_string` give us insight into "what" exception occurred, adding `app.exception_traceback` gives more insight into "why" the exception occurred. It also keeps us from having to manually add context for every exception in our code.

Add app.exception_traceback to context when an exception is thrown

---

beeline/propagation/test_honeycomb.py
beeline/propagation/test_w3c.py
beeline/test_trace.py

The custom test runner is not configured to include warnings the its
output. While this is a configurable options on Python 3.2+, given this
codebase is 2.7-compatible, I have not updated the configuration.
These were detected by running the test suite via
`python -m unittest discover` under Python 3.8 rather than
`poetry run tests` which uses the custom test runner.

Fix deprecations related to unittest usage

---

beeline/patch/requests.py

When using the Python `or` keyword in a string interpolation, it behaves differently to when you use it in assignment. This PR resolves an instance of this issue in the requests library patch. This helps avoid situations where the span name would be `requests_None`.
This code snippet demonstrates the issue:
```python
print("Hello %s" % None or "Dave")
name = None or "Dave"
print("Hello %s" % name)
```
I found this issue when making requests via the `request` library's `Session` object. This code is a minimum reproduction of the issue including the existing `beeline-python` release.
```python
import beeline
import requests
from beeline.patch.requests import *
def check_if_span_name_is_broken_presend_hook(event):
if 'name' in event and event['name'] == 'requests_None':
raise …
```

Fix requests patch to correctly build span name

---

beeline/patch/requests.py

The class `requests.Response` defines `__bool__` as:
```python
class Response(object):
...
def __bool__(self):
"""Returns True if :attr:`status_code` is less than 400.
This attribute checks if the status code of the response is between
400 and 600 to see if there was a client error or a server error. If
the status code, is between 200 and 400, this will return True. This
is **not** a check to see if the response code is ``200 OK``.
"""
return self.ok
```
This resulted in spans for requests with [400,600) status codes not including `content_type`, `content_length` or `status_code` in the span context, even when they were available.

Fix requests patch context omission for [400,600) status codes

---

beeline/propagation/test_w3c.py
beeline/propagation/w3c.py

Receiving OTEL instrumentation ignores spans coming with the 00 sampled flag.
This is a stop-gap measure to ensure w3c parser hooks work with an OTEL receiver. Ideally, we would like to set the sampled flag based on an actual sampler, but that requires further investigation.

Default w3c sampled flag to 01

---

beeline/middleware/awslambda/__init__.py
beeline/middleware/awslambda/test_awslambda.py

Trace field names match the ones used in `Tracer`:
https://github.com/honeycombio/beeline-python/blob/2ab8dea5d195096755199ac9badfe671f408bb9d/beeline/trace.py#L74-L78
closes https://github.com/honeycombio/beeline-python/issues/153

Capture exception details in AWS Lambda middleware.

---

beeline/middleware/django/__init__.py

Addresses #138
Django 3.1 deprecated the `is_ajax` method on `HttpRequest` and added a `RemovedInDjango40Warning`. The [release notes state](https://docs.djangoproject.com/en/3.1/releases/3.1/#id2):
> If you are writing your own AJAX detection method, request.is_ajax() can be reproduced exactly as request.headers.get('x-requested-with') == 'XMLHttpRequest'.

Avoid using deprecated Django request.is_ajax()

---

beeline/middleware/flask/__init__.py
beeline/middleware/flask/test_flask.py

Fixes https://github.com/honeycombio/beeline-python/issues/159
When this happens it causes a server error in the application.

Handle stringifying more types of parameters in flask DB middleware

---

.gitignore
examples/flask/README.md
examples/flask/app.py
examples/flask/pyproject.toml

- Add example app using Flask (initial plan to migrate from examples repo but the gatekeeper example is much more involved; this is a more basic example)
- Add a few more items to `.gitignore` for virtual environment and other local files
- Add example app with Flask; auto-instrumentation and manual span with trace context

Add example app using Flask

---

beeline/middleware/flask/__init__.py

- Closes #164 
- ... or, more specifically, this at least addresses [the comment added to that issue](https://github.com/honeycombio/beeline-python/issues/164#issuecomment-966485347), which seems like it may be the same as the initial poster.
- The flask middleware has a function `_teardown_request` that adds error fields if there is an exception, and is only used when `signals.signals_available` is True. This function sends the event only in the case of an exception... but if the exception is already being handled by error handlers, this event is never sent because it's no longer an exception. when it hits this code. This PR moves the `send_event` outside of the if block to ensure the event is always sent, regardless of whether it was an exception (or an already-handled exception).

[flask] Close trace regardless of exception

---

beeline/middleware/flask/__init__.py

- Follow up on comment on #190.
- Although the potential second `send_event()` is a noop, it's better to avoid that.
- Remove status code check for `beeline.finish_trace` and only check `not signals.signals_available`. 
There are no tests specifically testing against Flask with Signals. To confirm behavior, I added blinker (simple usage to ensure `signals_available` is True) and a basic error handler to EGS and tested name-service before and after changes with and without year-service also running.
```py
from blinker import Namespace
my_signals = Namespace()
model_saved = my_signals.signal('model-saved')
```
...
```py
@app.errorhandler(Exception)
def basic_error(e):
return 'An error occurred: ' + str(e), 500
```
Traces should have root spans and behavior is unchanged.

[flask] fix: Remove condition on status code

---

.bumpversion.cfg
CHANGELOG.md
RELEASING.md
beeline/version.py
pyproject.toml

Prepares the v2.17.3 release
- Updates version to 2.17.3
- Adds changelog entry
- Fix bumpversion config so it will run
- Update release docs to use updated bump2version command

Prepare v2.17.3 release

---

beeline/__init__.py
beeline/propagation/default.py
beeline/test_trace.py
beeline/trace.py

- closes #188 
- preference: trace parser hook > honeycomb header > w3c header

parse w3c headers by default

---

.circleci/config.yml
CONTRIBUTING.md
README.md
beeline/trace.py
poetry.lock
pyproject.toml

- https://github.com/honeycombio/beeline-python/security/dependabot/poetry.lock/urllib3/open
- https://github.com/honeycombio/beeline-python/security/dependabot/poetry.lock/jinja2/open
- https://github.com/honeycombio/beeline-python/security/dependabot/poetry.lock/django/open
- updates https://github.com/honeycombio/telemetry-team/issues/163
- closes #193 
- urllib3 requires python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, <4 
- django is vulnerable below 2, so also have to drop 2.7 to drop django 1 entirely

drop python < 3.5 support, update vulnerable deps

---

beeline/middleware/django/__init__.py

This new `db.call_count` rollup field will set a value on the root span
equal to the number of times a SQL query is made in a Django request.
This metric allows folks to, out of the box, find N+1 query problems
before they show up as performance issues, and to differentiate the
simpler cases of N+1 performance problems from other, more complicated
ones.
Currently, there's no way to do "aggregate of aggregate" queries in
Honeycomb that would let folks sum up the number of times a given span
name (like the ones made in HoneyDBWrapper) shows up in trace and then
group by request.path (or similar groupings) to find the p90 (or similar
aggregate calcuation) of those sums.
That means the alternative to adding this metric would be for folks to
either 1) use latency as a proxy for performance …

add a db.call_count rollup field for number of database queries on django root spans

---

beeline/middleware/django/__init__.py

Out of #205 (and internal conversation at my org), adding a rollup field
that includes how much time was spent executing SQL queries was also
desirable for an out-of-the-box experience. This adds that field.
There was a name collision with the already existing `db.duration` here
and the similarly named variable in the Go beeline that is used for
total time, so we choose the `db.total_duration` name here.

add rollup SQL duration time to Django traces

---

beeline/__init__.py
beeline/propagation/__init__.py
beeline/propagation/honeycomb.py
beeline/propagation/test_honeycomb.py
beeline/test_trace.py
examples/hello-world/README.md
examples/hello-world/app.py
examples/hello-world/pyproject.toml

- closes #212 
Tracing scenario for environment-aware teams:
* Dataset no longer propagates across services for new environment key.
* Add field `service.name` in addition to already added `service_name`
* `ServiceName` "required"†. If unset, will warn and set `service_name` AND `service.name` to `unknown_service:<process>` or `unknown_service:language`.
* Service name is used to populate dataset name; if `unknown_service.*` then truncate to`unknown_service` for dataset name.
* Trim whitespace from dataset name
* `WriteKey` required. If unset, will warn.
* `Dataset` **ignored**. If unset, no warning (because no longer used). If set, will warn to clarify that it will be ignored in favor of service name.
Tracing scenario for classic (non-environment-aware) teams:
* Add field `service.name` …

feat: Add Environment & Services support

---

.bumpversion.cfg
CHANGELOG.md
beeline/version.py
pyproject.toml

Prepares the v3.3.1 release. We normally don't release just for dependency updates, but the django bump includes a security fix.
- Adds changelog entry
- Updates version to 3.3.1

Prepare v3.3.1 release

---

CHANGELOG.md
README.md

- A customer reported an issue where they accidentally adopted E&S behavior because they are using a bogus key to send data via FileTransmission.
- Explicitly state the 32 character key check for those using a bogus key with FileTransmission
- Updated README - Issues are typically preferred over support tickets, and the Contributors file isn't really necessary anymore

docs: using FileTransmission with classic requires 32 character key

---

beeline/test_trace.py
beeline/trace.py

Adds support for recording whether a span is a root or subroot span within the trace. Root means it is the very first span across all services and subroot means it is the first span within a given service.
When starting a new trace manually, via instrumentation or via propagation, `start_trace` is used so this will ensure that meta.span_type is correctly set.
- Closes #218
- Add is_root_span to start_span with default of `False`, adds `meta.span_type` if set
- Update start_trace to set it to `True`
- Update tests to verify new field is set correctly

Add meta.span_type to root/subroot spans

---

beeline/patch/test_urllib.py
beeline/propagation/__init__.py
beeline/propagation/honeycomb.py
pylint.rc

Beeline hasn't supported use under Python 2 for a while now, so we can remove compat code.
- Resolves #227 
- Removes uses of [six](https://pypi.org/project/six/)
Note: six is still a transitive dep via dev dependencies, so it still appears in the poetry.lock.
» poetry show --tree
mock 3.0.5 Rolling backport of unittest.mock for all Pythons
└── six *
pylint 2.6.2 python code static checker
└── astroid >=2.4.0,<2.5
└── six >=1.12,<2.0

drop unnecessary backwards compatibility (remove six)

---

beeline/middleware/django/__init__.py

- #169 
- closes #225 
- this was initially changed to stop using deprecated request.is_ajax()
- request.headers was a nicer wrapper for headers introduced in Django 2.2
- `self.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'` is the exact implementation of is_ajax

fix: Django < 2.2 does not have request.headers

---

.circleci/config.yml
README.md
beeline/__init__.py
beeline/aiotrace.py
beeline/internal.py
beeline/middleware/django/__init__.py
beeline/middleware/flask/__init__.py
beeline/middleware/flask/test_flask.py
beeline/middleware/wsgi.py
beeline/patch/requests.py
beeline/patch/urllib.py
beeline/propagation/honeycomb.py
beeline/propagation/test_w3c.py
beeline/propagation/w3c.py
beeline/test_internal.py
beeline/test_trace.py
beeline/trace.py
examples/flask/poetry.lock
examples/flask/pyproject.toml
poetry.lock
pyproject.toml

- closes #230
- Bump version of Python required to 3.7 or higher
- Resolve dependencies
- Follow updated pylint expectations, including using f strings instead of .format()
- The u prefix for strings is no longer necessary, since Python 3.0 strings are Unicode by default.
- with upgrades, we needed to switch from patching current_app to app_context() when testing flask middleware
- ensure Flask example app still works, had to manually resolve a transient dependency due to `ImportError: cannot import name 'soft_unicode' from 'markupsafe'`  
- note: unfortunately, the hello world example was broken when I arrived, should make follow up ticket!

Drop Support for Python 3.5 and 3.6 in Beeline

---

examples/flask/poetry.lock
examples/flask/pyproject.toml
poetry.lock
pyproject.toml

We're dropping support for Python versions passed end of life (3.5, 3.6) To support these language changes, we're bumping the minimum requirement of Libhoney in the latest Beeline to libhoney-py/2.3.0
See Python website for [more information](https://devguide.python.org/versions/#unsupported-versions) on supported versions.

Bump libhoney version to 2.3 (for python >3.7)

---

.bumpversion.cfg
CHANGELOG.md
beeline/version.py
pyproject.toml

- Bump Python requirement to version 3.7 or higher, resolve dependencies.
- Follow updated pylint expectations, including using f strings instead of .format()

[release] Prepare 3.5.0

---

.circleci/config.yml

- newer cimg/python docker images fail to run poetry install with Exit Code 1
- looks to be related to having ANSI characters in poetry output
- updating to latest python orb version that includes --no-ansi argument when doing poetry install

maint: fix ci build

---

beeline/__init__.py

- Addresses internal bug that shows "beeline-python/{VERSION}" in the user agent rather than the parsed version number.
-

fix: Parse version number for beeline-python/{VERSION} addition

---

beeline/middleware/django/__init__.py

- closes #278 
- only add `db.last_insert_id` if `lastrowid` exists on the Cursor object.
A similar fix is already in place for [Flask middleware](https://github.com/honeycombio/beeline-python/blob/main/beeline/middleware/flask/__init__.py#L113). When using psycopg2, the `lastrowid` existed but came through as 0. When using psycopg3, the `lastrowid` doesn't exist, which caused an exception.
The below screenshot shows a before and after for this fix.

fix: fix error when cursor.lastrowid doesnt exist

---

.bumpversion.cfg
CHANGELOG.md
RELEASING.md
beeline/version.py
pyproject.toml

- prep release v3.5.2
- bump version from 3.5.1 to 3.5.2
- update changelog
- update releasing notes for added detail/clarity as seen in some of our newer active repos

rel: prep release v3.5.2

---

.circleci/config.yml

Update poetry publish step to use the new API token instead of a username and password.
- Update the publish step to use an API token

maint: Update poetry publish to use API token

---

README.md

- relates to #300 
Currently, the maximum supported Flask version is 2.3. Update the README.md to reflect that.

docs: document maximum supported Flask version is 2.3
