beeline/trace.py, beeline/version.py, setup.py
Fix for https://github.com/honeycombio/beeline-python/issues/20
=> add default args to new_traced_event method

README.md, beeline/__init__.py, beeline/internal.py, beeline/trace.py, beeline/version.py, setup.py
depends on https://github.com/honeycombio/beeline-python/pull/24
We've had several requests for a better way to see what's going on in the beeline. Is it configured correctly? Are we trying to send events? Adds optional debug logging.
=> Add verbose mode

beeline/test_trace.py, beeline/trace.py, beeline/version.py, setup.py
This keeps things consistent with the Go beeline
=> [tracing] propagate trace fields to earlier spans

beeline/__init__.py, beeline/test_beeline.py, beeline/version.py, setup.py
fixes https://github.com/honeycombio/beeline-python/issues/42
=> [tracing] Add function decorator 'wrap' to API

beeline/__init__.py, beeline/internal.py, beeline/test_beeline.py, beeline/test_trace.py, beeline/trace.py, beeline/version.py, setup.py
Fixes https://github.com/honeycombio/beeline-python/issues/46.
Found some references to older code that also needed to be cut out.
=> 2.4.2 - fixes issue in tracing context manager and some minor issues

beeline/__init__.py, beeline/test_beeline.py
Tracing and threading is awkard because of the need to explicitly copy trace state between threadlocal storage. Our docs recommend this approach: https://docs.honeycomb.io/getting-data-in/python/beeline/#threading-and-traces
However, this can be undesirable because it creates a new span at the start of the thread, when the interesting contest is further into the threaded function.
Adding a decorator here to pass trace state over to a threaded function without the added baggage of a new span.
=> Add decorator to pass trace context between threads

beeline/__init__.py
We have quite a bit of documentation describing how to handle prefork models: https://docs.honeycomb.io/getting-data-in/python/beeline/#using-the-python-beeline-with-python-pre-fork-models
Unfortunately, there are many ways to get it wrong and if you somehow initialize the beeline before the fork and after the fork, your new forked processes will not work correctly because the transmission thread will get left behind with the parent process. Debugging this is painful and we should just work around this scenario by ensuring that calls to `init` are safe no matter where they happen.
To help with this, I am adding code to store the initializing process ID. If a fork happens and the beeline object is copied to the new process via copy-on-write, we'll be able to detect this and correctly …
=> Support reinitialization after forking

beeline/patch/jinja2.py
Add a patch for timing how long it takes to render Jinja2 templates.
=> patch: add jinja2 patch

.circleci/config.yml, beeline/patch/jinja2.py, beeline/patch/test_jinja2.py, beeline/patch/test_urllib.py, beeline/patch/urllib.py, beeline/test_suite.py, setup.py
urllib patch testing could probably be more exhaustive, but I want to at least make sure that the code paths run.
=> [patch] add tests for jinja2 and urllib patches

CHANGELOG.md, beeline/test_trace.py, beeline/trace.py
Convert our trace and span ID generation to be compatible with w3c trace and spans.
=> Generate W3C compatible trace and span IDs

.bumpversion.cfg, beeline/version.py, pyproject.toml
Bump versions, tagging for release when merged.
=> Release version 2.12.2

.bumpversion.cfg, beeline/version.py, pyproject.toml
Release beeline version 2.13.0
=> Bump version: 2.13.0-dev0 → 2.13.0

beeline/propagation/__init__.py, beeline/propagation/honeycomb.py, beeline/propagation/test_honeycomb.py, beeline/test_trace.py, beeline/trace.py
Adds support for reading the dataset from the honeycomb propagation headers and setting the dataset for the trace appropriately.
=> Support dataset in Honeycomb propagation headers

.circleci/config.yml
- Removes build events so that third party PRs can be built
- Uses circle ci matrix builds to reduce config complexity
- Uses python orb to reduce config complexity
=> Remove build events, update build

.bumpversion.cfg, CHANGELOG.md, beeline/version.py, pyproject.toml
=> Prepare v2.16.0 release

beeline/middleware/starlette/__init__.py
This adds a middleware implementation for the Starlette ASGI server.
No tests added for now, wanted to get a 👍 / 👎 on this before spending time figuring out y'alls testing setup.
Fixes #95.
=> Add middleware for starlette

.bumpversion.cfg, CHANGELOG.md, beeline/version.py, pyproject.toml
=> Prepare patch release

.bumpversion.cfg, CHANGELOG.md, beeline/version.py, pyproject.toml
Updates the package version to v2.16.2 and the change log with commits since last release.
=> Prepare v2.16.2 release

beeline/middleware/django/__init__.py, beeline/middleware/django/test_django.py
Django streaming responses[1] return their "response," and then
repeatedly yield from their `.streaming_content` iterator to generate
the body.  Ending the request when the response is returned thus omits
all of the time spent streaming the response -- and by then the
HoneyDBWrapper's context has also been exited, which means any
database queries therein are also not traced.
Explicitly examine responses to determine if they are streaming --
and, if so, delay closing the root trace for the response until the
end of the streaming content.
[1] https://docs.djangoproject.com/en/3.2/ref/request-response/#streaminghttpresponse-objects
=> Support streaming responses.

.bumpversion.cfg, CHANGELOG.md, CONTRIBUTING.md, README.md, RELEASING.md, beeline/version.py, pyproject.toml
- Releasing!
- Version bump!
- Updated instructions on how to version bump!
- Updated instructions on how to release!
=> Prepare v2.17.1

.circleci/config.yml
=> ci: add python 3.9 and 3.10 to test matrix

.bumpversion.cfg, CHANGELOG.md, beeline/version.py, pyproject.toml
- Version bump and changelog update for release.
=> Prepare v2.18.0

.bumpversion.cfg, CHANGELOG.md, RELEASING.md, beeline/version.py, pyproject.toml
=> prepare 3.0.0 release

.bumpversion.cfg, CHANGELOG.md, beeline/version.py, pyproject.toml
- Release prep: version bump, changelog update.
=> Prepare v3.1.0

.bumpversion.cfg, CHANGELOG.md, beeline/version.py, pyproject.toml
=> prepare 3.2.0 release

.bumpversion.cfg, CHANGELOG.md, beeline/version.py, pyproject.toml
=> prepare 3.3.0 release

.bumpversion.cfg, CHANGELOG.md, beeline/version.py, pyproject.toml
Prepares the 3.4.0 release.
- Updates version to 3.4.0
- Adds changelog entry
=> Prepare 3.4.0 release

.bumpversion.cfg, CHANGELOG.md, beeline/version.py, pyproject.toml
=> release: prep v3.4.1

beeline/middleware/flask/__init__.py
Occasionally the start time when executing the after cursor handler doesn't have the start time set. This fix make sure we only attempt to calculate the duration if we have a start time.
- Fixes #158 
Executing the after cursor handler when a start time is not present doesn't result in an error.
NOTE: This doesn't attempt to resolve why we sometime execute the after cursor handler when a start time is not present.
=> fix: Only try to calculate query duration when we have start time

.bumpversion.cfg, CHANGELOG.md, beeline/version.py, pyproject.toml
Prepares the v3.5.1 release.
- Updates version in version.py, pyproject.toml and bumpversion.cfg
- Adds changelog entry
=> rel: Prepare v3.5.1 release

README.md
=> maint: update otel link in readme
